version: '3.1'                                #Docker-Compose Version 

services:                                      #Auflistng der Services 

  ghost:                                       #Ghost-Service
    image: ghost:1-alpine                      #image wird festgelegt
    container_name: ghost                      #container_name 
    restart: always                            #Nachdem erstellen Neustarten
    ports:                                     #Verwendete Ports definieren
      - 8080:2368
    environment:
      database__client: mysql
      database__client: mysql
      database__connection__host: mySQL        #Verlinkung zur Datenbank 
      database__connection__user: User         #Benutzername festlegen 
      database__connection__password: Qawsed123 #Benutzerpasswort festlegen 
      database__connection__database: ghost    #Service festlegen zu welchem sich die Datenbamnk verbinden muss

  mySQL:
    image: mysql:5.7                           #image wird festgelegt
    restart: always                            #Nachdem erstellen Neustarten
    container_name: mySQL                      #container_name
    environment:
      MYSQL_ROOT_PASSWORD: Qawsed123

networks:                                 # Anfang allgemeine Netzwerkkonfiguration
  Net1:                                   # Netzwerk Net1 erstellt