version: '3.1'

services:

  ghost:
    image: ghost:1-alpine
    restart: always
    ports:
      - 8080:2368
    environment:
      database__client: mysql
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example


volumes:                                  # Anfang Volume
  db_data: {}                             # Neues Volume
networks:                                 # Anfang allgemeine Netzwerkkonfiguration
  Net1:                                   # Netzwerk Net1 erstellt