# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

	#Diese VM-Box wird für den Webserver verwendet
  config.vm.box = "ubuntu/xenial64"
  # Create a private network, which allows host-only access to the machine
  # Eine fixe IP geben.
  config.vm.network "private_network", ip: "10.71.13.12"


  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"
  
  #Der aktuelle Ordner wird unter /var/www/html als Share Folder eingehängt
  #das Index-File wird auch dort abegelgt, somit kann dies gleich bezogen werden
  config.vm.synced_folder ".", "/var/www/html"  

#Virtualbox wird als VMprovider genutzt
  config.vm.provider "virtualbox" do |vb|

  #Customize the amount of memory on the VM:
    vb.memory = "4024"
  end

  #Install Apache2 und ufw. ufw erlaubt ssh, http und IPs im 24-Netz 10.71.13.0.
    config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y apache2
     apt-get update
     apt-get install -y ufw
     ufw allow ssh
     ufw allow http
     ufw allow from 10.71.13.0/24
	# Nachdem Neustart muss die Firewall manuell aktiviert werden. Dies mit "y" während des Startup bestätigen
     yes Y | ufw enable
  SHELL
end