# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.


  config.vm.box = "ubuntu/xenial64"
  # Create a private network, which allows host-only access to the machine
  # Für mich definierte IP wird konfiguriert.
  config.vm.network "private_network", ip: "10.71.13.12"


  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"
  
  #Es wird aus dem aktuellen Ordner ein shared Folder gemacht, der unter /var/www/html eingehängt wird.
  #das Index-FIle kann in dem gleichen Ordner abgelegt werden, somit bzeiht der Webserver diesen Index.
  config.vm.synced_folder ".", "/var/www/html"  

#Virtualbox wird als VMprovider genutzt
  config.vm.provider "virtualbox" do |vb|

  #Customize the amount of memory on the VM:
    vb.memory = "4024"
  end

  #Install Apache2 und ufw. ufw erlaubt ssh, http und IPs vom 24-Netz 10.71.13.0.
    config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y apache2
     apt-get update
     apt-get install -y ufw
     ufw allow ssh
     ufw allow http
     ufw allow from 10.71.13.0/24
	# Es muss neugestartet werden, dabei muss die Firewall manuell eingeschaltet werden. Somit muss man beim Startup mit Y bestätigen
     yes Y | ufw enable
  SHELL
end